"""add unique constraints and date types

Revision ID: 5a3bba16388a
Revises: acc5406da64c
Create Date: 2026-06-18 16:18:59.189209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3bba16388a'
down_revision: Union[str, Sequence[str], None] = 'acc5406da64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE deadline_table SET week_string = NULL WHERE week_string = ''")
    op.execute("UPDATE deadline_table SET deadline = NULL WHERE deadline = ''")
    op.execute("UPDATE menu_table SET week_string = NULL WHERE week_string = ''")
    op.execute("UPDATE menu_table SET date = NULL WHERE date = ''")
    op.execute("UPDATE orders_table SET date = NULL WHERE date = ''")
    op.execute("UPDATE orders_table SET week_string = NULL WHERE week_string = ''")
    op.execute("UPDATE orders_table SET submitted_at = NULL WHERE submitted_at = ''")
    op.alter_column('deadline_table', 'week_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='week_string::date')
    op.alter_column('deadline_table', 'deadline',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='deadline::timestamp without time zone')
    op.create_index(op.f('ix_deadline_table_week_string'), 'deadline_table', ['week_string'], unique=True)
    op.alter_column('menu_table', 'week_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='week_string::date')
    op.alter_column('menu_table', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='date::date')
    op.alter_column('orders_table', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='date::date')
    op.alter_column('orders_table', 'week_string',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='week_string::date')
    op.alter_column('orders_table', 'submitted_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='submitted_at::timestamp without time zone')
    op.create_index(op.f('ix_staff_table_email'), 'staff_table', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_table_email'), table_name='staff_table')
    op.alter_column('orders_table', 'submitted_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('orders_table', 'week_string',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('orders_table', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('menu_table', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('menu_table', 'week_string',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_deadline_table_week_string'), table_name='deadline_table')
    op.alter_column('deadline_table', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('deadline_table', 'week_string',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('ix_orders_staff_id', table_name='orders_table')
    op.drop_index('ix_orders_menu_item_id', table_name='orders_table')
    # ### end Alembic commands ###
