"""initial

Revision ID: 91bcfd72d0c6
Revises: 
Create Date: 2026-06-17 12:20:34.004485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bcfd72d0c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_string', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_table_id'), 'deadline_table', ['id'], unique=False)
    op.create_table('menu_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_string', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_table_id'), 'menu_table', ['id'], unique=False)
    op.create_table('staff_table',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('hash_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_table_staff_id'), 'staff_table', ['staff_id'], unique=False)
    op.create_table('orders_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('week_string', sa.String(), nullable=True),
    sa.Column('menu_title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_table.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_table_id'), 'orders_table', ['id'], unique=False)

    # Missing Indexes on Foreign Keys
    # orders_table.staff_id and orders_table.menu_item_id have no explicit indexes. 
    # JOINs will get slower as data grows.
    # Fix: Add indexes via new migration:
    # In the upgrade() function:
    op.create_unique_constraint('uq_staff_email', 'staff_table', ['email'])
    op.create_unique_constraint('uq_deadline_week', 'deadline_table', ['week_string'])
    op.create_index('ix_orders_staff_id', 'orders_table', ['staff_id'])
    op.create_index('ix_orders_menu_item_id', 'orders_table', ['menu_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders_table')
    op.drop_table('orders_table')
    op.drop_index(op.f('ix_staff_table_staff_id'), table_name='staff_table')
    op.drop_table('staff_table')
    op.drop_index(op.f('ix_menu_table_id'), table_name='menu_table')
    op.drop_table('menu_table')
    op.drop_index(op.f('ix_deadline_table_id'), table_name='deadline_table')
    op.drop_table('deadline_table')
    # ### end Alembic commands ###
