"""add status to menu_table

Revision ID: acc5406da64c
Revises: 91bcfd72d0c6
Create Date: 2026-06-17 13:04:11.769997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc5406da64c'
down_revision: Union[str, Sequence[str], None] = '91bcfd72d0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_table', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_table', 'status')
    # ### end Alembic commands ###
